services:
  postgres:
    image: postgres:16
    container_name: fastapi-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123124
    volumes:
      - fastapi_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fastapi

networks:
    fastapi:
        driver: bridge

volumes:
  fastapi_data: