CREATE SCHEMA IF NOT EXISTS ktor;

CREATE TABLE IF NOT EXISTS ktor.user (
    id uuid DEFAULT gen_random_uuid(),
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);