name: Docker
run-name: Build and push Docker image
on:
  workflow_call:
    inputs:
      docker-username:
        required: true
        type: string
        description: 'DockerHub username'
      docker-password:
        required: true
        type: string
        description: 'DockerHub password'
      docker-tag:
        required: true
        type: string
        description: 'Docker image tag'
      version:
        required: true
        type: string
        description: 'Project version'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v5
        with:
          username: ${{ inputs.docker-username }}
          password: ${{ inputs.docker-password }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: |
            ${{ inputs.docker-tag }}:${{ inputs.version }}
            ${{ inputs.docker-tag }}:latest
