name: Pipeline CI
run-name: Run pipeline CI on Python code
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  ci:
    name: Project Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read project version
        id: project-version
        run: echo "version=$(cat ./version.txt)" >> $GITHUB_OUTPUT

      - name: Project version
        run: echo ${{ steps.project-version.outputs.version }}

  python-lint:
    name: Python Lint
    uses: amartins-alexandre/github-actions/.github/workflows/python-lint.yml@main

#  python-test:
#    name: Python Test
#    uses: amartins-alexandre/github-actions/.github/workflows/python-test.yml@main

  docker-image:
    name: Docker Image
    uses: amartins-alexandre/github-actions/.github/workflows/docker.yml@main
    needs:
      - python-lint
    with:
      docker-username: ${{ secrets.DockerUsername }}
      docker-password: ${{ secrets.DockerPassword }}
      docker-tag: ${{ secrets.DockerUsername }}/user-fastapi
      version: ${{ steps.project-version.outputs.version }}