name: Python lint
run-name: Run Python lint on Python code
on:
  pull_request:
  workflow_call:
jobs:
    lint:
        name: Python Lint
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Set up Python 3.10
            uses: actions/setup-python@v5
            with:
              python-version: "3.10"

          - name: Install Pipenv dependencies
            run: |
              python -m pip install --upgrade pip
              pip install pipenv
              pipenv install

          - name: Run Python lint
            run: |
              pipenv install black
              pipenv run black .
